trigger:
- master

pool:
  name: MyWindowsAgent

stages:

# ---------- BUILD ----------
- stage: Build
  jobs:
  - job: BuildJob
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'

    - script: |
        npm install
        npm run build

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: build
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/app.zip

    - publish: $(Build.ArtifactStagingDirectory)/app.zip
      artifact: drop


# ---------- DEPLOY ----------
- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: drop

          - task: AzureWebApp@1
            inputs:
              azureSubscription: AzureConnection
              appName: shuja-react-app123
              package: $(Pipeline.Workspace)/drop/app.zip
